spring:
  application:
    name: dm-item-provider
  datasource:
    url: jdbc:mysql://192.168.9.151:3306/dm_item?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 192.168.9.151
    port: 5672
    username: guest
    password: guest
  redis:
    database: 0
    host: 192.168.9.151
    port: 6379
    user: root
    password: 123456
    timeout: 3000
  activemq:
    broker-url: tcp://192.168.9.151:61616?jms.optimizeAcknowledge=true&jms.optimizeAcknowledgeTimeOut=30000&jms.redeliveryPolicy.maximumRedeliveries=10
    user: admin
    password: admin
    packages:
    trust-all: true
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml


---
spring:
  profiles: provider1
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  client:
    service-url:
       defaultZone: http://root:123456@192.168.9.151:7776/eureka/
#      defaultZone: http://root:123456@localhost:9000/eureka/
#      defaultZone: http://root:123456@localhost:9000/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 7023

---
spring:
  profiles: provider2
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  client:
    service-url:
        defaultZone: http://root:123456@192.168.9.151:7776/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 7022



